[2025-09-03 15:45:37] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-09-03 15:49:07] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 12, "rules_count": 4}
[2025-09-03 15:49:07] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 12, "rules_count": 4}
[2025-09-03 15:49:08] [INFO] [system] System event: ML model loaded successfully | Component: fraud_ml_model | Severity: INFO | Data: {"model_path": "C:\\Users\\HP\\Desktop\\projects\\safeNetAi\\backend\\models\\fraud_isolation.joblib"}
[2025-09-03 15:49:08] [INFO] [email_service] Sending transaction notification to abassi.loay@gmail.com for transaction 296
[2025-09-03 15:49:10] [INFO] [email_service] Transaction notification sent successfully to abassi.loay@gmail.com
[2025-09-03 15:49:10] [INFO] [system] System event: Transaction notification sent successfully | Component: email_service | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61, "transaction_id": 296, "status": "COMPLETED", "risk_level": "LOW", "risk_score": 23}
[2025-09-03 15:49:10] [INFO] [django.server] "POST /api/client/transactions/ HTTP/1.1" 201 107
[2025-09-03 15:49:42] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 12, "rules_count": 4}
[2025-09-03 15:49:42] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 12, "rules_count": 4}
[2025-09-03 15:49:42] [INFO] [system] System event: ML model loaded successfully | Component: fraud_ml_model | Severity: INFO | Data: {"model_path": "C:\\Users\\HP\\Desktop\\projects\\safeNetAi\\backend\\models\\fraud_isolation.joblib"}
[2025-09-03 15:49:42] [INFO] [email_service] Attempting to send OTP email to abassi.loay@gmail.com
[2025-09-03 15:49:42] [INFO] [email_service] Email settings - Backend: django.core.mail.backends.smtp.EmailBackend, Host: smtp.gmail.com, Port: 587, User: abassi.loay23@gmail.com, TLS: True, SSL: False
[2025-09-03 15:49:43] [INFO] [email_service] OTP email sent successfully to abassi.loay@gmail.com. OTP: 192432
[2025-09-03 15:49:43] [INFO] [system] System event: OTP email sent successfully | Component: email_service | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61}
[2025-09-03 15:49:43] [INFO] [system] System event: Transaction OTP created and sent successfully | Component: transactions | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61, "transaction_id": 297, "otp_id": 16}
[2025-09-03 15:49:43] [WARNING] [system] System event: Transaction requires OTP verification due to risk rules or AI assessment | Component: transactions | Severity: WARNING | Data: {"transaction_id": 297, "risk_score": 53, "triggers": ["Large transfer: $15000.00 > $10000.0"], "ml_score": 0.5828239235242251, "user_id": 61, "reason": "risk_rules"}
[2025-09-03 15:49:43] [INFO] [django.server] "POST /api/client/transactions/ HTTP/1.1" 201 261
[2025-09-03 15:50:48] [INFO] [django.server] "OPTIONS /api/client/transactions/297/verify_otp/ HTTP/1.1" 200 0
[2025-09-03 15:50:48] [INFO] [system] System event: Transaction OTP verified successfully | Component: transactions | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61, "transaction_id": 297, "otp_id": 16}
[2025-09-03 15:50:48] [INFO] [email_service] Sending transaction notification to abassi.loay@gmail.com for transaction 297
[2025-09-03 15:50:50] [INFO] [email_service] Transaction notification sent successfully to abassi.loay@gmail.com
[2025-09-03 15:50:50] [INFO] [system] System event: Transaction notification sent successfully | Component: email_service | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61, "transaction_id": 297, "status": "COMPLETED", "risk_level": "MEDIUM", "risk_score": 53}
[2025-09-03 15:50:50] [INFO] [django.server] "POST /api/client/transactions/297/verify_otp/ HTTP/1.1" 200 114
[2025-09-03 15:50:54] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 15:50:54] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 5861
[2025-09-03 15:50:54] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 15:50:54] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 5861
[2025-09-03 15:51:31] [INFO] [django.server] "OPTIONS /api/auth/login/ HTTP/1.1" 200 0
[2025-09-03 15:51:31] [WARNING] [django.request] Unauthorized: /api/auth/login/
[2025-09-03 15:51:31] [WARNING] [django.server] "POST /api/auth/login/ HTTP/1.1" 401 172
[2025-09-03 15:51:31] [INFO] [django.server] "OPTIONS /api/auth/refresh/ HTTP/1.1" 200 0
[2025-09-03 15:51:31] [ERROR] [django.request] Internal Server Error: /api/auth/refresh/
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\rest_framework_simplejwt\views.py", line 46, in post
    serializer.is_valid(raise_exception=True)
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 116, in validate
    user := get_user_model().objects.get(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\Desktop\projects\safeNetAi\backend\venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
apps.users.models.User.DoesNotExist: User matching query does not exist.
[2025-09-03 15:51:31] [ERROR] [django.server] "POST /api/auth/refresh/ HTTP/1.1" 500 134297
[2025-09-03 15:51:47] [INFO] [django.server] "POST /api/auth/login/ HTTP/1.1" 200 647
[2025-09-03 15:51:47] [INFO] [django.server] "OPTIONS /api/client/profile/me/ HTTP/1.1" 200 0
[2025-09-03 15:51:47] [INFO] [django.server] "OPTIONS /api/client/transactions/ HTTP/1.1" 200 0
[2025-09-03 15:51:47] [INFO] [django.server] "OPTIONS /api/client/profile/me/ HTTP/1.1" 200 0
[2025-09-03 15:51:47] [INFO] [django.server] "OPTIONS /api/client/transactions/ HTTP/1.1" 200 0
[2025-09-03 15:51:47] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 15:51:47] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 15:51:47] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 5861
[2025-09-03 15:51:47] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 5861
[2025-09-03 15:52:50] [INFO] [django.server] "GET /admin/ HTTP/1.1" 200 15503
[2025-09-03 15:52:53] [INFO] [django.server] "GET /admin/risk/clientprofile/ HTTP/1.1" 200 46944
[2025-09-03 15:52:53] [INFO] [django.server] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-03 15:52:55] [INFO] [django.server] "GET /admin/risk/clientprofile/80/change/ HTTP/1.1" 200 27843
[2025-09-03 15:52:55] [INFO] [django.server] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-03 15:53:16] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 12, "rules_count": 4}
[2025-09-03 15:53:16] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 12, "rules_count": 4}
[2025-09-03 15:53:16] [INFO] [system] System event: ML model loaded successfully | Component: fraud_ml_model | Severity: INFO | Data: {"model_path": "C:\\Users\\HP\\Desktop\\projects\\safeNetAi\\backend\\models\\fraud_isolation.joblib"}
[2025-09-03 15:53:16] [INFO] [email_service] Sending transaction notification to abassi.loay@gmail.com for transaction 298
[2025-09-03 15:53:18] [INFO] [email_service] Transaction notification sent successfully to abassi.loay@gmail.com
[2025-09-03 15:53:18] [INFO] [system] System event: Transaction notification sent successfully | Component: email_service | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61, "transaction_id": 298, "status": "COMPLETED", "risk_level": "LOW", "risk_score": 18}
[2025-09-03 15:53:18] [INFO] [django.server] "POST /api/client/transactions/ HTTP/1.1" 201 107
[2025-09-03 15:57:59] [INFO] [django.server] "GET /admin/risk/clientprofile/80/change/ HTTP/1.1" 200 27843
[2025-09-03 15:57:59] [INFO] [django.server] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-03 16:00:18] [WARNING] [django.request] Bad Request: /api/client/transactions/
[2025-09-03 16:00:18] [WARNING] [django.server] "POST /api/client/transactions/ HTTP/1.1" 400 128
[2025-09-03 16:00:37] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 12, "rules_count": 4}
[2025-09-03 16:00:37] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 12, "rules_count": 4}
[2025-09-03 16:00:37] [INFO] [system] System event: ML model loaded successfully | Component: fraud_ml_model | Severity: INFO | Data: {"model_path": "C:\\Users\\HP\\Desktop\\projects\\safeNetAi\\backend\\models\\fraud_isolation.joblib"}
[2025-09-03 16:00:37] [INFO] [email_service] Attempting to send OTP email to abassi.loay@gmail.com
[2025-09-03 16:00:37] [INFO] [email_service] Email settings - Backend: django.core.mail.backends.smtp.EmailBackend, Host: smtp.gmail.com, Port: 587, User: abassi.loay23@gmail.com, TLS: True, SSL: False
[2025-09-03 16:00:40] [INFO] [email_service] OTP email sent successfully to abassi.loay@gmail.com. OTP: 700685
[2025-09-03 16:00:40] [INFO] [system] System event: OTP email sent successfully | Component: email_service | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61}
[2025-09-03 16:00:40] [INFO] [system] System event: Transaction OTP created and sent successfully | Component: transactions | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61, "transaction_id": 299, "otp_id": 17}
[2025-09-03 16:00:40] [WARNING] [system] System event: Transaction requires OTP verification due to risk rules or AI assessment | Component: transactions | Severity: WARNING | Data: {"transaction_id": 299, "risk_score": 44, "triggers": ["High frequency: 6 transactions in 2.0 hour(s)"], "ml_score": 0.480161714929228, "user_id": 61, "reason": "risk_rules"}
[2025-09-03 16:00:40] [INFO] [django.server] "POST /api/client/transactions/ HTTP/1.1" 201 269
[2025-09-03 16:01:01] [INFO] [django.server] "OPTIONS /api/client/transactions/299/verify_otp/ HTTP/1.1" 200 0
[2025-09-03 16:01:01] [INFO] [system] System event: Transaction OTP verified successfully | Component: transactions | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61, "transaction_id": 299, "otp_id": 17}
[2025-09-03 16:01:01] [INFO] [email_service] Sending transaction notification to abassi.loay@gmail.com for transaction 299
[2025-09-03 16:01:03] [INFO] [email_service] Transaction notification sent successfully to abassi.loay@gmail.com
[2025-09-03 16:01:03] [INFO] [system] System event: Transaction notification sent successfully | Component: email_service | Severity: INFO | Data: {"user_email": "abassi.loay@gmail.com", "user_id": 61, "transaction_id": 299, "status": "COMPLETED", "risk_level": "MEDIUM", "risk_score": 44}
[2025-09-03 16:01:03] [INFO] [django.server] "POST /api/client/transactions/299/verify_otp/ HTTP/1.1" 200 114
[2025-09-03 16:01:07] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 16:01:07] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 16:01:07] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 6443
[2025-09-03 16:01:07] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 6443
[2025-09-03 16:35:03] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 13, "rules_count": 4}
[2025-09-03 16:35:03] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 13, "rules_count": 4}
[2025-09-03 17:03:24] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-09-03 17:03:35] [INFO] [django.utils.autoreload] C:\Users\HP\Desktop\projects\safeNetAi\backend\apps\transactions\views.py changed, reloading.
[2025-09-03 17:03:36] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-09-03 17:03:46] [INFO] [django.server] "OPTIONS /api/client/transactions/ HTTP/1.1" 200 0
[2025-09-03 17:03:46] [INFO] [django.server] "OPTIONS /api/client/profile/me/ HTTP/1.1" 200 0
[2025-09-03 17:03:46] [INFO] [django.server] "OPTIONS /api/client/profile/me/ HTTP/1.1" 200 0
[2025-09-03 17:03:46] [INFO] [django.server] "OPTIONS /api/client/transactions/ HTTP/1.1" 200 0
[2025-09-03 17:03:46] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 17:03:46] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 17:03:46] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 6443
[2025-09-03 17:03:46] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 6443
[2025-09-03 17:03:58] [INFO] [django.server] "GET /admin/risk/clientprofile/80/change/ HTTP/1.1" 200 27843
[2025-09-03 17:03:58] [INFO] [django.server] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-03 17:04:22] [INFO] [django.server] "OPTIONS /api/auth/login/ HTTP/1.1" 200 0
[2025-09-03 17:04:23] [WARNING] [django.request] Bad Request: /api/auth/login/
[2025-09-03 17:04:23] [WARNING] [django.server] "POST /api/auth/login/ HTTP/1.1" 400 44
[2025-09-03 17:04:29] [INFO] [django.server] "POST /api/auth/login/ HTTP/1.1" 200 638
[2025-09-03 17:04:29] [INFO] [django.server] "OPTIONS /api/admin/dashboard/stats/ HTTP/1.1" 200 0
[2025-09-03 17:04:29] [INFO] [django.server] "OPTIONS /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 0
[2025-09-03 17:04:29] [INFO] [django.server] "OPTIONS /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 0
[2025-09-03 17:04:29] [INFO] [system] Dashboard stats requested by admin admin@safenetai.com
[2025-09-03 17:04:29] [INFO] [django.server] "GET /api/admin/dashboard/stats/ HTTP/1.1" 200 243
[2025-09-03 17:04:29] [INFO] [system] Dashboard stats requested by admin admin@safenetai.com
[2025-09-03 17:04:29] [INFO] [django.server] "GET /api/admin/dashboard/stats/ HTTP/1.1" 200 243
[2025-09-03 17:04:29] [INFO] [system] Recent activity requested by admin admin@safenetai.com
[2025-09-03 17:04:29] [INFO] [django.server] "GET /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 7975
[2025-09-03 17:04:29] [INFO] [system] Recent activity requested by admin admin@safenetai.com
[2025-09-03 17:04:29] [INFO] [django.server] "GET /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 7975
[2025-09-03 17:04:35] [INFO] [django.server] "OPTIONS /api/admin/clients/ HTTP/1.1" 200 0
[2025-09-03 17:04:35] [INFO] [django.server] "OPTIONS /api/admin/clients/ HTTP/1.1" 200 0
[2025-09-03 17:04:36] [INFO] [django.server] "GET /api/admin/clients/ HTTP/1.1" 200 22974
[2025-09-03 17:04:36] [INFO] [django.server] "GET /api/admin/clients/ HTTP/1.1" 200 22974
[2025-09-03 17:04:44] [INFO] [system] Recent activity requested by admin admin@safenetai.com
[2025-09-03 17:04:44] [INFO] [django.server] "GET /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 7975
[2025-09-03 17:04:44] [INFO] [system] Dashboard stats requested by admin admin@safenetai.com
[2025-09-03 17:04:44] [INFO] [django.server] "GET /api/admin/dashboard/stats/ HTTP/1.1" 200 243
[2025-09-03 17:04:44] [INFO] [system] Dashboard stats requested by admin admin@safenetai.com
[2025-09-03 17:04:44] [INFO] [django.server] "GET /api/admin/dashboard/stats/ HTTP/1.1" 200 243
[2025-09-03 17:04:44] [INFO] [system] Recent activity requested by admin admin@safenetai.com
[2025-09-03 17:04:44] [INFO] [django.server] "GET /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 7975
[2025-09-03 17:04:46] [INFO] [django.server] "GET /api/admin/clients/ HTTP/1.1" 200 22974
[2025-09-03 17:04:46] [INFO] [django.server] "GET /api/admin/clients/ HTTP/1.1" 200 22974
[2025-09-03 17:05:06] [INFO] [django.server] "OPTIONS /api/admin/fraud-alerts/ HTTP/1.1" 200 0
[2025-09-03 17:05:06] [INFO] [django.server] "OPTIONS /api/admin/fraud-alerts/ HTTP/1.1" 200 0
[2025-09-03 17:05:06] [INFO] [django.server] "GET /api/admin/fraud-alerts/ HTTP/1.1" 200 9740
[2025-09-03 17:05:06] [INFO] [django.server] "GET /api/admin/fraud-alerts/ HTTP/1.1" 200 9740
[2025-09-03 17:05:23] [INFO] [django.server] "OPTIONS /api/admin/transactions/ HTTP/1.1" 200 0
[2025-09-03 17:05:23] [INFO] [django.server] "OPTIONS /api/admin/transactions/ HTTP/1.1" 200 0
[2025-09-03 17:05:23] [INFO] [django.server] "GET /api/admin/transactions/ HTTP/1.1" 200 13030
[2025-09-03 17:05:23] [INFO] [django.server] "GET /api/admin/transactions/ HTTP/1.1" 200 13030
[2025-09-03 17:05:25] [INFO] [django.server] "GET /api/admin/clients/ HTTP/1.1" 200 22974
[2025-09-03 17:05:25] [INFO] [django.server] "GET /api/admin/clients/ HTTP/1.1" 200 22974
[2025-09-03 17:05:28] [INFO] [system] Dashboard stats requested by admin admin@safenetai.com
[2025-09-03 17:05:28] [INFO] [system] Recent activity requested by admin admin@safenetai.com
[2025-09-03 17:05:28] [INFO] [django.server] "GET /api/admin/dashboard/stats/ HTTP/1.1" 200 243
[2025-09-03 17:05:28] [INFO] [django.server] "GET /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 7975
[2025-09-03 17:05:28] [INFO] [system] Dashboard stats requested by admin admin@safenetai.com
[2025-09-03 17:05:28] [INFO] [django.server] "GET /api/admin/dashboard/stats/ HTTP/1.1" 200 243
[2025-09-03 17:05:28] [INFO] [system] Recent activity requested by admin admin@safenetai.com
[2025-09-03 17:05:28] [INFO] [django.server] "GET /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 7975
[2025-09-03 17:05:30] [INFO] [django.server] "GET /api/admin/fraud-alerts/ HTTP/1.1" 200 9740
[2025-09-03 17:05:31] [INFO] [django.server] "GET /api/admin/fraud-alerts/ HTTP/1.1" 200 9740
[2025-09-03 17:05:33] [INFO] [system] Dashboard stats requested by admin admin@safenetai.com
[2025-09-03 17:05:33] [INFO] [django.server] "GET /api/admin/dashboard/stats/ HTTP/1.1" 200 243
[2025-09-03 17:05:33] [INFO] [system] Recent activity requested by admin admin@safenetai.com
[2025-09-03 17:05:33] [INFO] [django.server] "GET /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 7975
[2025-09-03 17:05:33] [INFO] [system] Dashboard stats requested by admin admin@safenetai.com
[2025-09-03 17:05:33] [INFO] [django.server] "GET /api/admin/dashboard/stats/ HTTP/1.1" 200 243
[2025-09-03 17:05:33] [INFO] [system] Recent activity requested by admin admin@safenetai.com
[2025-09-03 17:05:33] [INFO] [django.server] "GET /api/admin/dashboard/recent_activity/ HTTP/1.1" 200 7975
[2025-09-03 17:05:50] [INFO] [django.server] "POST /api/auth/login/ HTTP/1.1" 200 647
[2025-09-03 17:05:50] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 17:05:50] [INFO] [django.server] "GET /api/client/profile/me/ HTTP/1.1" 200 469
[2025-09-03 17:05:50] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 6443
[2025-09-03 17:05:50] [INFO] [django.server] "GET /api/client/transactions/ HTTP/1.1" 200 6443
[2025-09-03 17:08:45] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 13, "rules_count": 4}
[2025-09-03 17:08:45] [ERROR] [django.request] Internal Server Error: /api/client/transactions/
[2025-09-03 17:08:45] [ERROR] [django.server] "POST /api/client/transactions/ HTTP/1.1" 500 39
[2025-09-03 17:09:45] [INFO] [system] System event: RiskEngine initialized | Component: risk_engine | Severity: INFO | Data: {"thresholds_count": 13, "rules_count": 4}
[2025-09-03 17:09:45] [ERROR] [django.request] Internal Server Error: /api/client/transactions/
[2025-09-03 17:09:45] [ERROR] [django.server] "POST /api/client/transactions/ HTTP/1.1" 500 39
